version: '3.8'

services:
  web:
    image: php:7.4-apache
    container_name: crud_teste_php
    ports:
      - "8081:80"
    volumes:
      - ./public:/var/www/html
    depends_on:
      - db
    command: ["apache2-foreground"]

  db:
    image: mysql:5.7
    container_name: crud_teste_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: crud_teste
    ports:
      - "3306:3306"
